"""auto-vote

Revision ID: bc0d836abd2a
Revises: 5d76f89089bb
Create Date: 2023-12-08 14:06:36.935044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bc0d836abd2a'
down_revision: Union[str, None] = '5d76f89089bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('v_user_id', sa.Integer(), nullable=False),
    sa.Column('v_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['v_post_id'], ['posts.id'], onupdate='NO ACTION', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['v_user_id'], ['users.id'], onupdate='NO ACTION', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('v_user_id', 'v_post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
